service:
  name: algolia-search-users

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*-${self:provider.stage}"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  seed:
    handler: handler.seed
    timeout: 30
    environment:
      USERS_DB_NAME: "algolia-search-users-${self:provider.stage}"

resources:
  Resources:
    users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "algolia-search-users-${self:provider.stage}"
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
